---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: pcfdemo

caches:
  - path: pcfdemo/m2
  
outputs:
  - name: build

run:
  path: pcfdemo/ci/tasks/ft.sh
  args: [
    --input-dir, pcfdemo,
    --output-dir, build,
    --input-manifest, pcfdemo/manifest.yml,
    --artifactId, pcf-demo,
    --packaging, war
  ]  
